- shell:
    - command: ./init-scripts/initial-configure.sh
      description: Initializing Dotfiles
      stdin: true
      stdout: true
    - command: ./init-scripts/setup-conventional-commits.sh
      description: Setting up conventional commits
      stdin: true
      stdout: true
