- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/aerospace: macos/aerospace
    ~/.config/borders: macos/borders
    ~/.config/karabiner: macos/karabiner
    ~/.config/sketchybar: macos/sketchybar
    ~/.hammerspoon: macos/hammerspoon
    ~/Brewfile:
      force: true
      path: macos/Brewfile
    ~/Library/Application Support/Sublime Merge:
      path: apps/Sublime Merge
    ~/Library/Application Support/Sublime Text:
      path: apps/Sublime Text
    ~/Library/Application Support/Cursor/User/keybindings.json: apps/Cursor/keybindings.json
    ~/Library/Application Support/Cursor/User/settings.json: apps/Cursor/settings.json
