- link:
    ~/.config/aerospace: config/aerospace
    ~/.config/borders: config/borders
    ~/.config/karabiner: config/karabiner
    ~/.config/sketchybar: config/sketchybar
    ~/.hammerspoon: hammerspoon
    ~/Brewfile:
      force: true
      path: Brewfile
    ~/Library/Application Support/Sublime Merge:
      path: Sublime Merge
    ~/Library/Application Support/Sublime Text:
      path: Sublime Text
