- link:
    ~/.config/gh: config/gh
    ~/.config/ghostty: config/ghostty
    ~/.config/lazygit: config/lazygit
    ~/.config/marksman: config/marksman
    ~/.config/nvim: config/nvim
    ~/.config/nvim-vscode: config/nvim-vscode
    ~/.config/starship: config/starship
    ~/.default-npm-packages: default-npm-packages
    ~/.gitconfig: git/gitconfig
    ~/.hushlogin: hushlogin