- link:
    ~/.config/bat: config/bat
    ~/.config/nushell: config/nushell
    ~/.config/btop: config/btop
    ~/.config/fish: config/fish
    ~/.config/kitty: config/kitty
    ~/.config/lazydocker: config/lazydocker
    ~/.config/mise: config/mise
    ~/.config/television: config/television
    ~/.config/tmux: config/tmux
    ~/.config/yazi: config/yazi
    ~/.config/zellij: config/zellij
    ~/.config/aichat: config/aichat
