#!/usr/bin/env lua

os.execute(
	"[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)"
)

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")
